### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by EagleoutIce** [Code-Inspect/vscode-flowr#1]
We want the basic vscode plugin structure (maybe with :sparkles: <https://code.visualstudio.com/api/get-started/your-first-extension> :sparkles:)

**Comment by Ellpeck** [comment]
I guess this is sort of part of the initial setup too, but it would probably make sense to move this out into its own issue: Should we just copy the eslint settings and related linting ci actions from the main repository, or make our own (based on what)?
