### ISSUE TITLE
CI Setup to automatically release builds

### ISSUE THREAD

**Issue by Ellpeck** [Code-Inspect/vscode-flowr#26]
At first I was thinking that it would be nice if new releases were created and tagged automatically if the package version in the `package.json` is changed in a push to main, but I don't actually know if that's, like, easy to detect?

So if that's not an option, I think it would be best if any tags pushed to main would trigger a GitHub & (later?) VS Marketplace release.

**Comment by EagleoutIce** [comment]
i prefer the way i handle it for flowr -> a commit may contain a magic prefix which then causes the creation of a patch/minor/major - with non-monotonic versions being deployable manually
