### ISSUE TITLE
Track selection/marked positions

### ISSUE THREAD

**Issue by ManuelHentschel** [Code-Inspect/vscode-flowr#76]
Great project, looks really useful!

Below some ideas for modifications, which might be nice to have:
- Allow slices with multiple cursors. The flowr API already seems to support this, so it's just a matter of extracting the right info from `editor.selections`
- Auto-update the slice to follow the current selection
- Allow the user to set "markers", which are used as slice criteria. The user can then edit the code to clean up dependencies and see live updates of the slice.
- Use `vscode.TextDocumentContentProvider` to output reconstructed slices. This way the contents of the slice can be updated continuously without opening new temporary documents (particularly useful for the previous two points)
- (Remove activation events from `package.json`. The extension activates automatically when commands are called, and as far as I can see, these are the only ways to interact with the extension at the moment.)

I have implemented a first draft of these suggestions on the branch https://github.com/ManuelHentschel/vscode-flowr/tree/modifications. They still need some polishing and error checking, but the main ideas should work using the following commands.
- `vscode-flowr.trackPosition`
- `vscode-flowr.showPositionSliceInEditor`
- `vscode-flowr.trackSelection`
- `vscode-flowr.showSelectionSliceInEditor`
- Using `alt + left-click`, multiple cursors can be set, which should then work with slice commands

Let me know if you would be interested in including any of this.

**Comment by EagleoutIce** [comment]
First of all: thank you very, very much!
In fact, we are interested in all of these updates - especially the automatic update sounds like a great idea!

Feel free to open a merge request whenever you are ready or ping me if you want to me to (at least try to) integrate your current changes!
